version: '1'
services:
  production:
    build:
      context: "./"
      dockerfile: Dockerfile
    networks:
      - ship
    environment:
      APP_ENV: production
    volumes:
      - "./megabee-deeplink:/app/src"
    ports:
      - "80:3000"

networks:
  ship:
    name: ship_network