version: '3.3'
services:
  landing:
    build:
      context: "./"
      dockerfile: Dockerfile
    networks:
      - ship
    environment:
      APP_ENV: development
    volumes:
      - "./:/app"
    ports:
      - "3000:3000"
networks:
  ship:
    name: ship_network