import Head from 'next/head'
import Image from 'next/image'
import { useState } from 'react'
import styles from '../styles/Home.module.css'
import getOS, { checkDeepLink } from '../util/check-os';

export default function Home() {
  const [infoPlatform, setInfo] = useState(); 

  const onPress = () => {
    checkDeepLink();
  }

  const onChangeStateApp = () => {

      console.log('In background: ',document.hidden);
      // Modify behavior…
  }

  useEffect(() => {
    document.addEventListener("visibilitychange", onChangeStateApp);

    return () => {
      document.removeEventListener('visibilitychange', onChangeStateApp)
    }
  }, [])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Test deep link from browser {infoPlatform}!
        </h1>

        <div className={styles.grid}>
          <div onClick={onPress} id='open-app'  className={styles.card}>
            <h2>Open &rarr;</h2>
            <p>Open app with deep link</p>
          </div>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
